version: '3.2'
services:
  todos-server:
    build: todos-server/.
    command: ./todos-server --grpc-port=3000 --db-path=/data/tasks.db
    ports:
      - "9170:3000"
    volumes:
      - type: bind
        target: /data
        source: ./todos-server/data
  graphql-server:
    build: graphql-server/.
    command: ./graphql-server
    ports:
      - "9181:8080"