// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_server

import (
	"time"
)

type DeleteTodo struct {
	TodoID int `json:"todoId"`
}

type NewTodo struct {
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Reminder    *time.Time `json:"reminder"`
}

type ReadTodo struct {
	TodoID int `json:"todoId"`
}

type UpdateTodo struct {
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	TodoID      int        `json:"todoId"`
	IsDone      *bool      `json:"isDone"`
	Reminder    *time.Time `json:"reminder"`
}
